import type { Metadata } from "next"
import "./globals.css"
import Footer from "@/components/common/footer/Footer"
import Navbar from "@/components/Navbar"
import { Montserrat } from "next/font/google"
import ArrowHandler from "@/components/common/ArrowHandler"

// Import Montserrat
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="font-sans">
        <Navbar />
        {children}
        <Footer />
        <ArrowHandler /> 
      </body>
    </html>
  )
}
